[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "muon"
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [
    { name = "moskomule", email = "moskomule@users.noreply.github.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "torch>=2.9.0",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://moskomule.github.io/muon"
Issues = "https://github.com/moskomule/muon/issues"
Source = "https://github.com/moskomule/muon"

[tool.hatch.version]
path = "muon/__about__.py"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.12", "3.13"]

[tool.hatch.envs.hatch-test]
installer = "uv"

[tool.hatch.envs.hatch-test.env-vars]
UV_DEFAULT_URL = "https://download.pytorch.org/whl/cpu https://pypi.org/simple"